// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BootstrapInteractionsController from "./bootstrap_interactions_controller"
application.register("bootstrap-interactions", BootstrapInteractionsController)

import ChatController from "./chat_controller"
application.register("chat", ChatController)

import DarkModeController from "./dark_mode_controller"
application.register("dark-mode", DarkModeController)

import ExpandableTextareaController from "./expandable_textarea_controller"
application.register("expandable-textarea", ExpandableTextareaController)

import ExternalModalController from "./external_modal_controller"
application.register("external-modal", ExternalModalController)

import SubtleChecklistController from "./subtle_checklist_controller"
application.register("subtle-checklist", SubtleChecklistController)

import ToastsController from "./toasts_controller"
application.register("toasts", ToastsController)

import TzController from "./tz_controller"
application.register("tz", TzController)
