inherit_from: .rubocop_todo.yml
require:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable

Layout/LineLength:
  Exclude:
    - 'features/step_definitions/**/*'

Metrics/AbcSize:
  Max: 25

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  Exclude:
    - 'config/**/*'
    - 'lib/tasks/**/*'

Rails/LexicallyScopedActionFilter:
  Exclude:
    - 'app/controllers/users/registrations_controller.rb'

Rails/SkipsModelValidations:
  AllowedMethods:
    - touch

RSpec/MultipleExpectations:
  Exclude:
    - 'spec/requests/**/*'

RSpec/NestedGroups:
  Max: 5

Style/Documentation:
  Enabled: false

Style/NumericLiterals:
  Exclude:
    - 'db/schema.rb'

Style/SpecialGlobalVars:
  EnforcedStyle: use_perl_names

Style/StringLiterals:
  Exclude:
    - 'db/schema.rb'

Style/SymbolArray:
  EnforcedStyle: percent

Style/WordArray:
  EnforcedStyle: percent
