inherit_from: .rubocop_todo.yml
require:
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable

Metrics/AbcSize:
  Max: 25

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  Exclude:
    - 'config/**/*'

Style/Documentation:
  Enabled: false

Style/NumericLiterals:
  Exclude:
    - 'db/schema.rb'

Style/SpecialGlobalVars:
  EnforcedStyle: use_perl_names

Style/SymbolArray:
  EnforcedStyle: percent

Style/WordArray:
  EnforcedStyle: percent

Style/StringLiterals:
  Exclude:
    - 'db/schema.rb'

Rails/SkipsModelValidations:
  AllowedMethods:
    - touch

Rails/LexicallyScopedActionFilter:
  Exclude:
    - 'app/controllers/users/registrations_controller.rb'
