services:
  app:
    build:
      context: ./
      dockerfile: docker/dev/Dockerfile
    command: bin/dev
    depends_on:
      - db
      - redis
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    volumes:
      - .:/rails
      - bundle-data:/usr/local/bundle

  db:
    image: postgres:16.2
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:7.2.4
    volumes:
      - redis-data:/var/lib/redis/data

volumes:
  bundle-data:
  redis-data:
  db-data:
