default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development: &dev
  <<: *default
  database: smolchat_development
  username: postgres
  password: postgres
  host: db

test:
  <<: *dev
  database: smolchat_test

production:
  <<: *default
  database: smolchat_production
  username: smolchat
  password: <%= ENV["SMOLCHAT_DATABASE_PASSWORD"] %>
